name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checjout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando login"
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        echo "Fin del login"

    - name: Build Docker Image y Push
    	run: |
      	docker build -t danito90/docker-graphql:0.0.2 --push .
      	docker build -t danito90/docker-graphql:latest --push .
       
    # - name: Push Docker Image
    #   run: |
    #     docker push -t danito90/docker-graphql:0.0.2
    #     docker push -t danito90/docker-graphql:latest
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
